Added login logic, logout logic, and worked with real backend
AsaturHakhverdyan/Linz_Optik_Wholesale pull request #2
Opened 2022-11-17 12:27 UTC by AsaturHakhverdyan

2022-11-17 13:38 UTC, hrachocode requested changes

2022-11-17 13:38 UTC, hrachocode commented on src/App.tsx
> +},[]);
```suggestion
useEffect(() => {
  (async () => {
    if(!localStorage.getItem("jwt_token")){
      navigate("/login")
    }
  })()
},[]);
```

2022-12-12 13:39 UTC, IshkhanDavtyan requested changes

2022-12-12 13:39 UTC, IshkhanDavtyan commented on src/Components/home/HomePage.tsx
> +  const BASE_URL: string = process.env.REACT_APP_BASE_URL as string;
use one of these types ( :string or as string)

2022-12-12 13:39 UTC, IshkhanDavtyan commented on src/Components/home/components/InformationBlock.tsx
> +}) => {
Create interface for this types

2022-12-12 13:39 UTC, IshkhanDavtyan commented on src/Components/home/components/Pagination.tsx
> +  setCurrentPage: React.Dispatch<React.SetStateAction<number>>;
Create interface for this types

2022-12-12 13:39 UTC, IshkhanDavtyan commented on src/Components/home/components/Pagination.tsx
> +  }
get Array of pages like this
 const paginationCount=Array.from({length: Math.ceil(totalCount/productPerPage)}, (_, i) => i + 1)

2022-12-12 13:39 UTC, IshkhanDavtyan commented on src/Components/home/components/Pagination.tsx
> +  };
create utils.ts file inside component direction and move these functions there (decrementPaginationCount,incrementPaginationCount)

2022-12-12 13:39 UTC, IshkhanDavtyan commented on src/Components/home/components/Product.tsx
> +
cool :) , this function will be moved in utils.ts file

2022-12-12 13:39 UTC, IshkhanDavtyan commented on src/Components/leftbar/LeftBarMenu.tsx
> +  const BASE_URL: string = process.env.REACT_APP_BASE_URL as string;
use (:string or as string) one of types , these two are equivalent

2022-12-12 13:39 UTC, IshkhanDavtyan commented on src/Components/leftbar/LeftBarMenu.tsx
>    };
move this function to utils.ts file

2022-12-12 13:39 UTC, IshkhanDavtyan commented on src/Components/leftbar/components/LeftBarInfo.tsx
> +}) => {
Create interface for this types

2022-12-12 13:39 UTC, IshkhanDavtyan commented on src/Components/leftbar/components/LeftBarInfo.tsx
>    };
move this function to utils.ts file

2022-12-12 13:39 UTC, IshkhanDavtyan commented on src/Components/leftbar/components/LeftBarInfo.tsx
> +                  />
alt will be empty string if there is nothing to  describe image

2022-12-12 13:39 UTC, IshkhanDavtyan commented on src/Components/leftbar/components/LeftBarItem.tsx
> +}) => {
Create interface

2022-12-12 13:39 UTC, IshkhanDavtyan commented on src/Components/login/LoginForm.tsx
> +  const LOGIN_URL: string = process.env.REACT_APP_LOGIN_URL as string;
use one of type declaration (:string or as string)

2022-12-12 13:39 UTC, IshkhanDavtyan commented on src/Components/login/LoginForm.tsx
>    const formHendler = async (event: React.SyntheticEvent<HTMLFormElement>) => {
move this function to utils.ts file

2022-12-12 13:39 UTC, IshkhanDavtyan commented on src/Components/update/UpdatePassword.tsx
> +  const clickHandler = (event: React.SyntheticEvent<HTMLFormElement>) => {
move to utils.ts file

2022-12-14 13:39 UTC, hrachocode requested changes

2022-12-14 13:39 UTC, hrachocode commented on src/App.tsx
> +      if (!localStorage.getItem("jwt_token")) {
```suggestion
      if (!localStorage.getItem(LOCAL_STORAGE_KEYS.JWT_TOKEN)) {
```

export const LOCAL_STORAGE_KEYS = {
  JWT_TOKEN: "jwt_token",
  JWT_REFRESH_TOKEN: "jwt_refresh_token"
}

2022-12-14 13:39 UTC, hrachocode commented on src/App.tsx
> +        navigate("/login");
```suggestion
        navigate(PAGES.LOGIN);
```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/header/Header.tsx
> +  };
```suggestion

```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/header/Header.tsx
> +          <div className="">
```suggestion
          <div>
```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/header/Header.tsx
> +            <img src={logo} alt="" />
```suggestion
            <img src={logo} alt="logo" />
```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/header/Header.tsx
> +              search.length !== 0
```suggestion
              !!search.length
```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/header/components/ChooseComponent.tsx
>              onClick={() => setShow(!show)}
```suggestion
            onClick={() => toggleShow(!show)}
```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/header/components/SearchProduct.tsx
> +  const [isLoading, setisLoading] = useState<boolean>(false);
```suggestion
  const [isLoading, setIsLoading] = useState<boolean>(false);
```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/header/components/SearchProduct.tsx
> +          `${process.env.REACT_APP_BASE_URL}/wc/v3/products?search=${search}&consumer_key=ck_91dcee2c1dda0dee993904bc2e5f59fe6be3895d&consumer_secret=cs_5c79352efe06c166099b85d537767a28afe619e5`
use process.env here

2022-12-14 13:39 UTC, hrachocode commented on src/Components/header/components/SearchProduct.tsx
> +    }, 700);
```suggestion
    }, UNMOUNT_TIMEOUT_VALUE);
```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/header/components/SearchProduct.tsx
> +          {!searchProduct?.length && (
```suggestion
          {!searchProduct?.length ? (
```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/header/components/SearchProduct.tsx
> +            <Link to={`/product/${product.id}`} key={index}>
```suggestion
            <Link to={`${PAGES.PRODUCT}/${product.id}`} key={index}>
```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/header/components/SearchProduct.tsx
> +                    src={product.images[0].src}
```suggestion
                    src={product?.images?.[0]?.src}
```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/header/components/SearchProduct.tsx
> +                    <p className="text-[12px] text-gray-400">{product.sku}</p>
```suggestion
                    <p className="text-[12px] text-gray-400">{product?.sku}</p>
```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/header/components/SearchProduct.tsx
> +                    <h1 className="text-[14px]">{product.name}</h1>
```suggestion
                    <h1 className="text-[14px]">{product?.name}</h1>
```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/home/HomePage.tsx
> +  const [productPerPage] = useState<number>(9);
this is constant

2022-12-14 13:39 UTC, hrachocode commented on src/Components/home/HomePage.tsx
> +  const [totolCount, setTotalCount] = useState<number>(0);
this is contant?

2022-12-14 13:39 UTC, hrachocode commented on src/Components/home/components/Pagination.tsx
> +          {paginationCount.length > 1 && (
```suggestion
          {!!paginationCount.length && (
```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/home/components/Product.tsx
> +  const [sameProducts, setSameProducts] = useState<SingleProducts[] | undefined>();
```suggestion
  const [similiarProducts, setSimiliarProducts] = useState<SingleProducts[] | undefined>();
```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/home/components/Product.tsx
> +  const [Loading, setloading] = useState<boolean>(false);
names

2022-12-14 13:39 UTC, hrachocode commented on src/Components/home/components/Product.tsx
> +  }, [BASE_URL, id, CONSUMER_KEY, WC_V3]);
create custom hook

2022-12-14 13:39 UTC, hrachocode commented on src/Components/home/components/Product.tsx
> +  }, [BASE_URL, id, CONSUMER_KEY, WC_V3]);
because I saw a repeating code.

2022-12-14 13:39 UTC, hrachocode commented on src/Components/home/components/Product.tsx
> +      }
try catch finally

2022-12-14 13:39 UTC, hrachocode commented on src/Components/home/components/Product.tsx
> +  };
```suggestion

```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/home/components/Product.tsx
> +  }, [singleProduct?.description, singleProduct?.short_description]);
```suggestion

```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/home/components/Product.tsx
> +              className="mySwiper"
```suggestion
              {...defaultSLiderSettings}
              loop={true}
```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/home/components/Product.tsx
> +                    onClick={() => console.log("")}
```suggestion
                    ```

2022-12-14 13:39 UTC, hrachocode commented on src/Components/home/components/SameProducts.tsx
> +      }
use constants with defined numbers

2022-12-14 13:39 UTC, hrachocode commented on src/Components/leftbar/LeftBarMenu.tsx
> +  const BASE_URL = process.env.REACT_APP_BASE_URL as string;
export this from one file

2022-12-20 09:27 UTC, hrachocode requested changes

2022-12-20 09:27 UTC, hrachocode commented on src/Components/home/components/SingleProduct.tsx
> +        <SimilarProducts similarProducts={similarProducts} SimilarLoading={SimilarLoading} />
similarLoading

2022-12-20 09:27 UTC, hrachocode commented on src/Components/home/hooks/useBaseProductsCall.tsx
> +  const MinPriceQuery = searchParams.get("min_price") || "5000";
```suggestion
  const MinPriceQuery = searchParams.get(QUERY_PARAMS.MIN_PRICE) || "5000";
```

2022-12-22 09:49 UTC, hrachocode approved these changes

2022-12-22 09:59 UTC, merged